// This file was auto-generated by ML.NET Model Builder. 

using IrisRecognitionML.Model;
using System;

namespace IrisRecognitionML.ConsoleApp
{
	class Program
	{
		static void Main(string[] args)
		{
			// Create single instance of sample data from first line of dataset for model input
			ModelInput sampleData = new ModelInput()
			{
				Sepal_length = 5.1F,
				Sepal_width = 3.5F,
				Petal_length = 1.4F,
				Petal_width = 0.2F,
			};

			// Make a single prediction on the sample data and print results
			var predictionResult = ConsumeModel.Predict(sampleData);

			Console.WriteLine("Using model to make single prediction -- Comparing actual Variety with predicted Variety from sample data...\n\n");
			Console.WriteLine($"Sepal_length: {sampleData.Sepal_length}");
			Console.WriteLine($"Sepal_width: {sampleData.Sepal_width}");
			Console.WriteLine($"Petal_length: {sampleData.Petal_length}");
			Console.WriteLine($"Petal_width: {sampleData.Petal_width}");
			Console.WriteLine($"\n\nPredicted Variety value {predictionResult.Prediction} \nPredicted Variety scores: [{String.Join(",", predictionResult.Score)}]\n\n");
			Console.WriteLine("=============== End of process, hit any key to finish ===============");
			Console.ReadKey();
		}
	}
}
